"""Tests for the shared domain-event envelope (shared/events.py).

These are pure-logic tests — no DB, Redis, or network required.
They lock down the wire format that every service depends on.
"""
from __future__ import annotations

import json
import uuid
from datetime import datetime

import pytest

from shared.events import (
    DEFAULT_TENANT_ID,
    DomainEvent,
    EventType,
    STREAM_AFFILIATE,
    STREAM_AI_WORKER,
    STREAM_IDENTITY,
    STREAM_PLANNER,
)


def test_event_gets_autogenerated_id_and_timestamp():
    evt = DomainEvent(
        event_type=EventType.TRIP_CREATED,
        subject_id="trip-123",
        tenant_id=DEFAULT_TENANT_ID,
    )
    # event_id is a valid UUID string
    uuid.UUID(evt.event_id)
    assert isinstance(evt.occurred_at, datetime)
    assert evt.payload == {}
    assert evt.actor_user_id is None


def test_event_ids_are_unique_per_instance():
    a = DomainEvent(event_type=EventType.STAFF_CREATED, subject_id="s1", tenant_id=DEFAULT_TENANT_ID)
    b = DomainEvent(event_type=EventType.STAFF_CREATED, subject_id="s1", tenant_id=DEFAULT_TENANT_ID)
    # The envelope documents event_id as the idempotency key — must differ.
    assert a.event_id != b.event_id


def test_event_roundtrips_through_json():
    evt = DomainEvent(
        event_type=EventType.GENERATION_REQUESTED,
        subject_id="trip-9",
        tenant_id=DEFAULT_TENANT_ID,
        actor_user_id="user-1",
        payload={"destination": "Paris", "duration_days": 5},
    )
    wire = evt.model_dump_json()
    restored = DomainEvent.model_validate(json.loads(wire))
    assert restored.event_id == evt.event_id
    assert restored.event_type is EventType.GENERATION_REQUESTED
    assert restored.payload["destination"] == "Paris"


def test_subject_id_and_tenant_id_are_required():
    with pytest.raises(Exception):
        DomainEvent(event_type=EventType.TRIP_CREATED)  # type: ignore[call-arg]


def test_event_type_values_are_stable_strings():
    # Consumers match on these literal strings — guard against accidental renames.
    assert EventType.TRIP_BOOKED == "trip.booked"
    assert EventType.CUSTOMER_CREATED == "customer.created"
    assert EventType.GENERATION_COMPLETED == "generation.completed"


def test_stream_keys_are_distinct():
    streams = {STREAM_IDENTITY, STREAM_PLANNER, STREAM_AFFILIATE, STREAM_AI_WORKER}
    assert len(streams) == 4
