"""add profile images

Revision ID: 90e72a17bca8
Revises: 82f42a17bca8
Create Date: 2026-07-06 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e72a17bca8'
down_revision: Union[str, None] = '82f42a17bca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_profiles', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('customer_profiles', sa.Column('cover_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_profiles', 'cover_url')
    op.drop_column('customer_profiles', 'avatar_url')
    # ### end Alembic commands ###
