"""Add remaining community models

Revision ID: 0af0d6233ca9
Revises: bdbe75caf0c2
Create Date: 2026-06-24 04:25:43.113584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af0d6233ca9'
down_revision: Union[str, None] = 'bdbe75caf0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
