"""add meetup cost

Revision ID: 55644910a698
Revises: 0022_community_discover_saved
Create Date: 2026-08-25 09:47:28.049482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55644910a698'
down_revision: Union[str, None] = '0022_community_discover_saved'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsletter_subscribers')
    op.drop_index(op.f('ix_faq_feedback_item_id'), table_name='faq_feedback')
    op.drop_table('faq_feedback')
    op.drop_index(op.f('ix_activity_acceptance_stats_city'), table_name='activity_acceptance_stats')
    op.create_index(op.f('ix_activity_acceptance_stats_city_normalized'), 'activity_acceptance_stats', ['city_normalized'], unique=False)
    op.create_index(op.f('ix_activity_outcomes_customer_id'), 'activity_outcomes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_activity_outcomes_interaction_id'), 'activity_outcomes', ['interaction_id'], unique=False)
    op.create_index(op.f('ix_activity_outcomes_trip_id'), 'activity_outcomes', ['trip_id'], unique=False)
    op.drop_index(op.f('ix_chat_interactions_latency_ms'), table_name='chat_interactions', postgresql_where='(latency_ms IS NOT NULL)')
    op.create_index(op.f('ix_chat_interactions_session_id'), 'chat_interactions', ['session_id'], unique=False)
    op.drop_constraint(op.f('chat_messages_interaction_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'interaction_id')
    op.drop_column('chat_sessions', 'title')
    op.add_column('community_meetups', sa.Column('cost', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_destinations_embedding_hnsw'), table_name='destinations', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_constraint(op.f('hashtags_tag_key'), 'hashtags', type_='unique')
    op.alter_column('trip_activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trip_collaborators', 'invited_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trip_expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trip_expenses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trip_invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_trip_invite_token'), 'trip_invites', type_='unique')
    op.drop_index(op.f('ix_trip_invites_token'), table_name='trip_invites')
    op.create_index(op.f('ix_trip_invites_token'), 'trip_invites', ['token'], unique=True)
    op.drop_index(op.f('ix_trips_embedding_hnsw'), table_name='trips', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_trips_embedding_hnsw'), 'trips', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_trip_invites_token'), table_name='trip_invites')
    op.create_index(op.f('ix_trip_invites_token'), 'trip_invites', ['token'], unique=False)
    op.create_unique_constraint(op.f('uq_trip_invite_token'), 'trip_invites', ['token'], postgresql_nulls_not_distinct=False)
    op.alter_column('trip_invites', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trip_expenses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trip_expenses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trip_collaborators', 'invited_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trip_activities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(op.f('hashtags_tag_key'), 'hashtags', ['tag'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_destinations_embedding_hnsw'), 'destinations', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_column('community_meetups', 'cost')
    op.add_column('chat_sessions', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('interaction_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chat_messages_interaction_id_fkey'), 'chat_messages', 'chat_interactions', ['interaction_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_chat_interactions_session_id'), table_name='chat_interactions')
    op.create_index(op.f('ix_chat_interactions_latency_ms'), 'chat_interactions', ['latency_ms'], unique=False, postgresql_where='(latency_ms IS NOT NULL)')
    op.drop_index(op.f('ix_activity_outcomes_trip_id'), table_name='activity_outcomes')
    op.drop_index(op.f('ix_activity_outcomes_interaction_id'), table_name='activity_outcomes')
    op.drop_index(op.f('ix_activity_outcomes_customer_id'), table_name='activity_outcomes')
    op.drop_index(op.f('ix_activity_acceptance_stats_city_normalized'), table_name='activity_acceptance_stats')
    op.create_index(op.f('ix_activity_acceptance_stats_city'), 'activity_acceptance_stats', ['city_normalized'], unique=False)
    op.create_table('faq_feedback',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('helpful', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['faq_items.id'], name=op.f('faq_feedback_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('faq_feedback_pkey'))
    )
    op.create_index(op.f('ix_faq_feedback_item_id'), 'faq_feedback', ['item_id'], unique=False)
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('consent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('subscribed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('newsletter_subscribers_pkey')),
    sa.UniqueConstraint('email', name=op.f('uq_newsletter_subscribers_email'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
