"""add meetup capacity

Revision ID: 7eb5420bcb5a
Revises: 55644910a698
Create Date: 2026-08-25 10:44:58.931674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eb5420bcb5a'
down_revision: Union[str, None] = '55644910a698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_meetups', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_meetups', 'capacity')
    # ### end Alembic commands ###
