"""add meetup schedule and what_to_bring

Revision ID: 9c1a2e7f4b3d
Revises: 7eb5420bcb5a
Create Date: 2026-08-27 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c1a2e7f4b3d'
down_revision: Union[str, None] = '7eb5420bcb5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_meetups', sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('community_meetups', sa.Column('what_to_bring', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_meetups', 'what_to_bring')
    op.drop_column('community_meetups', 'schedule')
    # ### end Alembic commands ###
