"""add meetup category and meeting_link

Revision ID: f2a8b1c3d4e5
Revises: 9c1a2e7f4b3d
Create Date: 2026-08-27 00:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f2a8b1c3d4e5'
down_revision: Union[str, None] = '9c1a2e7f4b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_meetups', sa.Column('category', sa.String(length=20), nullable=True))
    op.add_column('community_meetups', sa.Column('meeting_link', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_meetups', 'meeting_link')
    op.drop_column('community_meetups', 'category')
    # ### end Alembic commands ###
