"""baseline schema

Revision ID: 42df932a98fe
Revises: 
Create Date: 2026-06-22 08:52:39.746325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42df932a98fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_segment_counts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_segment_counts_segment'), 'customer_segment_counts', ['segment'], unique=False)
    op.create_index(op.f('ix_customer_segment_counts_tenant_id'), 'customer_segment_counts', ['tenant_id'], unique=False)
    op.create_table('dashboard_metric_daily',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_metric_daily_metric_date'), 'dashboard_metric_daily', ['metric_date'], unique=False)
    op.create_index(op.f('ix_dashboard_metric_daily_metric_key'), 'dashboard_metric_daily', ['metric_key'], unique=False)
    op.create_index(op.f('ix_dashboard_metric_daily_tenant_id'), 'dashboard_metric_daily', ['tenant_id'], unique=False)
    op.create_table('staff_customer_counts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('count_customers', sa.Integer(), nullable=False),
    sa.Column('count_itineraries', sa.Integer(), nullable=False),
    sa.Column('count_pending', sa.Integer(), nullable=False),
    sa.Column('count_booked', sa.Integer(), nullable=False),
    sa.Column('count_created', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_customer_counts_staff_id'), 'staff_customer_counts', ['staff_id'], unique=False)
    op.create_index(op.f('ix_staff_customer_counts_tenant_id'), 'staff_customer_counts', ['tenant_id'], unique=False)
    op.create_table('trip_status_counts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('count_created', sa.Integer(), nullable=False),
    sa.Column('count_pending', sa.Integer(), nullable=False),
    sa.Column('count_booked', sa.Integer(), nullable=False),
    sa.Column('count_cancelled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_status_counts_customer_id'), 'trip_status_counts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_trip_status_counts_destination'), 'trip_status_counts', ['destination'], unique=False)
    op.create_index(op.f('ix_trip_status_counts_tenant_id'), 'trip_status_counts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trip_status_counts_tenant_id'), table_name='trip_status_counts')
    op.drop_index(op.f('ix_trip_status_counts_destination'), table_name='trip_status_counts')
    op.drop_index(op.f('ix_trip_status_counts_customer_id'), table_name='trip_status_counts')
    op.drop_table('trip_status_counts')
    op.drop_index(op.f('ix_staff_customer_counts_tenant_id'), table_name='staff_customer_counts')
    op.drop_index(op.f('ix_staff_customer_counts_staff_id'), table_name='staff_customer_counts')
    op.drop_table('staff_customer_counts')
    op.drop_index(op.f('ix_dashboard_metric_daily_tenant_id'), table_name='dashboard_metric_daily')
    op.drop_index(op.f('ix_dashboard_metric_daily_metric_key'), table_name='dashboard_metric_daily')
    op.drop_index(op.f('ix_dashboard_metric_daily_metric_date'), table_name='dashboard_metric_daily')
    op.drop_table('dashboard_metric_daily')
    op.drop_index(op.f('ix_customer_segment_counts_tenant_id'), table_name='customer_segment_counts')
    op.drop_index(op.f('ix_customer_segment_counts_segment'), table_name='customer_segment_counts')
    op.drop_table('customer_segment_counts')
    # ### end Alembic commands ###
