#!/usr/bin/env node
/**
 * Generates TypeScript types from each service's exported OpenAPI schema
 * (openapi/<service>.json, produced by scripts/export_openapi.py at the repo
 * root) into apps/web/src/app/api/generated/<service>.ts.
 *
 * Run `npm run codegen` to do both steps together.
 */
import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OPENAPI_DIR = join(__dirname, '..', '..', '..', 'openapi');
const OUT_DIR = join(__dirname, '..', 'src', 'app', 'api', 'generated');

if (!existsSync(OPENAPI_DIR)) {
  console.error(
    `No OpenAPI schemas found at ${OPENAPI_DIR}. Run "npm run codegen:openapi" first.`
  );
  process.exit(1);
}

mkdirSync(OUT_DIR, { recursive: true });

const schemaFiles = readdirSync(OPENAPI_DIR).filter((f) => f.endsWith('.json'));
if (schemaFiles.length === 0) {
  console.error(`No .json schemas in ${OPENAPI_DIR}.`);
  process.exit(1);
}

for (const file of schemaFiles) {
  const service = file.replace(/\.json$/, '');
  const schemaPath = join(OPENAPI_DIR, file);
  const ast = await openapiTS(new URL(`file://${schemaPath}`));
  const output = astToString(ast);
  const banner = `/* eslint-disable */\n// AUTO-GENERATED by scripts/codegen-api.mjs from openapi/${file}. Do not edit by hand.\n\n`;
  writeFileSync(join(OUT_DIR, `${service}.ts`), banner + output);
  console.log(`wrote src/app/api/generated/${service}.ts`);
}
