version = 5.7.0
archive_dir = /home/debin/projects/travel-planner/travlplanr/infra/letsencrypt/config/archive/dev.deepsynq.com
cert = /home/debin/projects/travel-planner/travlplanr/infra/letsencrypt/config/live/dev.deepsynq.com/cert.pem
privkey = /home/debin/projects/travel-planner/travlplanr/infra/letsencrypt/config/live/dev.deepsynq.com/privkey.pem
chain = /home/debin/projects/travel-planner/travlplanr/infra/letsencrypt/config/live/dev.deepsynq.com/chain.pem
fullchain = /home/debin/projects/travel-planner/travlplanr/infra/letsencrypt/config/live/dev.deepsynq.com/fullchain.pem
[renewalparams]
account = 15f127937f993d89aa300baf79baa909
config_dir = /home/debin/projects/travel-planner/travlplanr/infra/letsencrypt/config
work_dir = /home/debin/projects/travel-planner/travlplanr/infra/letsencrypt/work
logs_dir = /home/debin/projects/travel-planner/travlplanr/infra/letsencrypt/logs
authenticator = webroot
webroot_path = /home/debin/projects/travel-planner/travlplanr/infra/certbot-webroot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
dev.deepsynq.com = /home/debin/projects/travel-planner/travlplanr/infra/certbot-webroot
